apiVersion: certmanager.k8s.io/v1alpha
kind: Certificate
metadata:
  name: themayqueens-com-tils
spec:
  name: themayqueens-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: themayqueens.com
  dnsNames:
    - themayqueens.com
    - www.themayqueens.com
  acme:
    config:
      - http01:
        ingressClass: nginx
      domains:
        - themayqueens.com
        - www.themayqueens.com

